name: Docker Image CI for ros2 jazzy

on:
  push:
    branches:
      - jazzy

jobs:
  build_and_publish_jazzy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username robinheitz --password ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} ghcr.io
          docker build . -f Dockerfile --tag ghcr.io/robinheitz/ros:jazzy
          docker push ghcr.io/robinheitz/ros:jazzy
