name: Docker Image CI for ros1 noetic 

on:
  push:
    branches:
      - melodic

jobs:
  build_and_publish_humble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: | 
          docker login --username robinheitz --password ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} ghcr.io
          docker build . -f melodic.Dockerfile --tag ghcr.io/robinheitz/ros:melodic
          docker push ghcr.io/robinheitz/ros:melodic


